name: Force template compliance

on:
  issues:
    types: [opened]

jobs:
  templateComplianceChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce compliance
        if: startsWith(github.event.issue.title, '[BUG]') == 'true' && contains(github.event.issue.body, 'If you do not use this template for your issue, it will remain unanswered and automatically be closed') != 'true'
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Issue must use the bug template provided on issue creation.
            Auto-closing this issue.
