name: Update google fonts

on:
  schedule:
    - cron: '*/15 * * * * '
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish Google Fonts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.2.0

      - name: Install dependencies
        run: npm ci

      - name: Update google fonts
        env:
          GFONT_API_KEY: ${{ secrets.GFONT_API_KEY }}
        run: npm run update-fonts

      - name: Push changes to release branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: google-fonts-host
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
